### ISSUE TITLE
List contains returns true for checking if 2 exists in a list inserted with "2"

### ISSUE THREAD

**Issue by 1sand0s** [EngineeringSoftware/gobash#18]
### Minimum working example

```[bash]
#!/bin/bash                                                                                         
. src/util/list.sh

lst=$(List)
$lst add 1
$lst add 3
$lst add "2"
$lst contains 2
echo $? # returns 0
```

### 

This [line](https://github.com/EngineeringSoftware/gobash/blob/5e7da5387b4e50cb0674947d599830d8d4c49d89/src/util/list.sh#L169) essentially always does `string` compare which is true even when comparing "2" with 2.
```[bash]
if [ "${el}" = "${val}" ]; then 
	return $TRUE
fi
```

**Comment by gliga** [comment]
Thanks for the comment.

That example looks like something I would expect to see in bash.  Everything is string in a way; there is really no difference between "2" and 2 when used in bash line, like you did.
```
$lst add "2"
```
is no diff from
```
$lst add 2
```

Here is also more "native" bash example.

```
#!/bin/bash                                                                                                                                                                                   

x=2
z="2"

if [ ${x} = "${z}" ]; then
        echo "same"
fi
```
What do you expect to see as the result in this case?

**Comment by gliga** [comment]
Closing based on the comment above and in-person agreement.
